mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    # path('', views.AdListView.as_view()),
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),

]

mysite/autos/urls.py
from django.urls import path
from . import views

app_name='autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', views.MakeView.as_view(), name='make_list'),
    path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path 
from django.conf.urls import url
from django.views.static import serve
from polls.views import home
from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls' , namespace="home-polls") ),                                                                                           
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('hello/' , include("hello.urls")) , 
    path('autos' , include("autos.urls")) , 
    path("accounts/" , include("django.contrib.auth.urls")), 
    path('cats/', include('cats.urls')),
    path('ads/' , include('ads.urls')) , 
    path('accounting/', include('accounting.urls'))




]

mysite/autos/models.py
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.
class Make(models.Model):
    name = models.CharField(
        max_length=200,
        help_text= "please enter a make" ,
        validators= [MinLengthValidator(5,"Should greater than 5")]
    )

    def __str__(self):
        return self.name

class Auto(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    mileage = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    make = models.ForeignKey('Make', on_delete=models.CASCADE, null=False)

    # Shows up in the admin list
    def __str__(self):
        return self.nickname

mysite/autos/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView , CreateView , DeleteView 
from django.views.generic import ListView
from django.views import View
from .models import Make , Auto
from django.urls import reverse_lazy
# Create your views here.
class MainView(LoginRequiredMixin , View):
    def get(self , request):
        mc = Make.objects.all().count()
        al = Auto.objects.all()

        ctx = {
            'make_count': mc, 'auto_list': al
        }
        return render(request , "autos/main.html" , ctx)

class MakeView(LoginRequiredMixin , ListView):
    model = Make
    template_name = "autos/make_list.html"
    context_object_name = "make_list"

class MakeCreate(LoginRequiredMixin , CreateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:make_list')

class MakeUpdate(LoginRequiredMixin , UpdateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:make_list')

class MakeDelete(LoginRequiredMixin , DeleteView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:make_list')

class AutoCreate(LoginRequiredMixin,CreateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

class AutoUpdate(LoginRequiredMixin, UpdateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

class AutoDelete(LoginRequiredMixin, DeleteView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

mysite/autos/templates/autos/auto_confirm_delete.html
{% extends "home/base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the auto: {{ auto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/autos/templates/autos/auto_form.html
{% extends "home/base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/autos/templates/autos/auto_list.html
{% extends "home/base_bootstrap.html" %}

{% block content %}
  <h1>Auto List</h1>
  {% if auto_list %}
  <ul>

    {% for auto in auto_list %}
      <li>
          {{ auto.nickname }} ({{ auto.make }})
          (<a href="{% url 'autos:auto_update' auto.id %}">Update</a> |
          <a href="{% url 'autos:auto_delete' auto.id %}">Delete</a>) <br/>
          {{ auto.comments }} ({{ auto.mileage }} miles)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no autos in the library.</p>
  {% endif %}
  <p>
    {% if make_count > 0 %}
      <a href="{% url 'autos:auto_create' %}">Add an auto</a>
    {% else %}
      Please add a make before you add an auto.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'autos:make_list' %}">View makes</a> ({{ make_count }}) | 
    <a href="{% url 'autos:make_create' %}">Add a make</a>
  </p>
{% endblock %}

mysite/autos/templates/autos/main.html
{% extends "home/base_bootstrap.html" %}

{% block content %}
  <h1>Auto List</h1>
  {% if auto_list %}
  <ul>

    {% for auto in auto_list %}
      <li>
          {{ auto.nickname }} ({{ auto.make }})
          (<a href="{% url 'autos:auto_update' auto.id %}">Update</a> |
          <a href="{% url 'autos:auto_delete' auto.id %}">Delete</a>) <br/>
          {{ auto.comments }} ({{ auto.mileage }} miles)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no autos in the library.</p>
  {% endif %}
  <p>
    {% if make_count > 0 %}
      <a href="{% url 'autos:auto_create' %}">Add an auto</a>
    {% else %}
      Please add a make before you add an auto.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'autos:make_list' %}">View makes</a> ({{ make_count }}) | 
    <a href="{% url 'autos:make_create' %}">Add a make</a>
  </p>
{% endblock %}

mysite/autos/templates/autos/make_confirm_delete.html
{% extends "home/base_bootstrap.html" %}

{% block content %}

<h1>Delete Make</h1>

<p>Are you sure you want to delete the make: {{ make }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/autos/templates/autos/make_form.html
{% extends "home/base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/autos/templates/autos/make_list.html
{% extends "home/base_bootstrap.html" %}

{% block content %}
  <h1>Make List</h1>
  {% if make_list %}
  <ul>
    {% for make in make_list %}
      <li>
          {{ make.name }}
         (<a href="{% url 'autos:make_update' make.id %}">Update</a> |
          <a href="{% url 'autos:make_delete' make.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no makes in the library.</p>
  {% endif %}
  <p><a href="{% url 'autos:make_create' %}">Add a make</a></p>
  <p>
    <a href="{% url 'autos:all' %}">Back to autos</a>
  </p>
  <a href="{% url 'autos:make_list' %}">View makes</a> ({{ make_count }}) | 

{% endblock %}