mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    # path('', views.AdListView.as_view()),
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),

]

mysite/cats/urls.py
from django.urls import path
from . import views

app_name = "cats"
urlpatterns = [
    path('', views.CatList.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete')
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path 
from django.conf.urls import url
from django.views.static import serve
from polls.views import home
from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls' , namespace="home-polls") ),                                                                                           
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('hello/' , include("hello.urls")) , 
    path('autos' , include("autos.urls")) , 
    path("accounts/" , include("django.contrib.auth.urls")), 
    path('cats/', include('cats.urls')),
    path('ads/' , include('ads.urls')) , 
    path('accounting/', include('accounting.urls'))




]

mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

mysite/cats/views.py
from django.shortcuts import render
from django.views.generic import DeleteView , ListView , UpdateView , CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Cat, Breed
# Create your views here.

class CatList(LoginRequiredMixin , ListView):
    model = Cat

class CatCreate(LoginRequiredMixin , CreateView):
    model = Cat
    fields = "__all__"
    success_url = reverse_lazy("cats:all")

class CatUpdate(LoginRequiredMixin , UpdateView):
    model = Cat
    fields = "__all__"
    success_url = reverse_lazy("cats:all")

class CatDelete(LoginRequiredMixin , DeleteView):
    model = Cat
    success_url = reverse_lazy("cats:all")



class BreedView(LoginRequiredMixin , ListView):
    model = Breed

class BreedCreate(LoginRequiredMixin , CreateView):
    model = Breed
    fields = "__all__"
    success_url = reverse_lazy("cats:all")

class BreedUpdate(LoginRequiredMixin , UpdateView):
    model = Breed
    fields = "__all__"
    success_url = reverse_lazy("cats:all")

class BreedDelete(LoginRequiredMixin , DeleteView):
    model = Breed
    success_url = reverse_lazy("cats:all")

mysite/cats/templates/cats/breed_confirm_delete.html
{% extends 'home/base_bootstrap.html' %}

{% block content %}
<p>Are you Sure?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/cats/templates/cats/breed_form.html
{% extends 'home/base_bootstrap.html' %}

{% block content %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>

  {% endblock %}

mysite/cats/templates/cats/breed_list.html
{% extends 'home/base_bootstrap.html' %}

{% block content %}

<table>
    <tr>

        <th>breed</th>
        <th>Edit</th>
        <th>Delete</th>

    </tr>
    {% for breed in breed_list %}
        <tr>
 
            <td>{{ breed.name }}</td>
            <td><a href="{% url 'cats:breed_update' breed.id %}">Edit</a></td>
            <td><a href="{% url 'cats:breed_delete' breed.id %}">Delete</a></td>
        </tr>
        
    {% endfor %}

</table>

<ul>
    <a href="{% url 'cats:cat_create' %}">Add Cat</a>
</ul>
{% endblock %}

mysite/cats/templates/cats/cat_confirm_delete.html
{% extends 'home/base_bootstrap.html' %}

{% block content %}

<p>Are you Sure?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/cats/templates/cats/cat_form.html
{% extends 'home/base_bootstrap.html' %}

{% block content %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>

  {% endblock %}

mysite/cats/templates/cats/cat_list.html
{% extends 'home/base_bootstrap.html' %}

{% block content %}
<table>
    <tr>
        <th>nickname</th>
        <th>weight</th>
        <th>foods</th>
        <th>breed</th>
        <th>Edit</th>
        <th>Delete</th>

    </tr>
    {% for cat in cat_list %}
        <tr>
            <td>{{ cat.nickname }}</td>
            <td>{{ cat.weight }}</td>
            <td>{{ cat.foods }}</td>
            <td>{{ cat.breed }}</td>
            <td><a href="{% url 'cats:cat_update' cat.id %}">Edit</a></td>
            <td><a href="{% url 'cats:cat_delete' cat.id %}">Delete</a></td>
        </tr>
        
    {% endfor %}

</table>

<ul>
    <a href="{% url 'cats:cat_create' %}">Add Cat</a>
    <a href="{% url 'cats:breed_create' %}">Add Breed</a>
</ul>

{% endblock %}